version: '3.6'
services:
  mariadb:
    image: mariadb:11.2.2-jammy
    container_name: ${PROJECT}-mariadb
    restart: always
    mem_limit: 320M
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d:ro
    tmpfs:
      - /tmp:size=64M
    environment:
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_DATABASE=hexancore_dev
    ports:
      - 10020:3306
  postgres:
    image: bitnami/postgresql:15
    container_name: ${PROJECT}-postgress
    restart: always
    mem_limit: 256M
    tmpfs:
      - /tmp:size=64M
    environment:
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=hexancore_dev
    ports:
      - 10021:5432
